class Elements:
    def __init__(self):
        self.screen_block = "//*[@class='_3ixn']"
        self.download_your_info = \
            "//*[@class='fbSettingsListLink clearfix pvm phs']"
        self.format_dropdown_menu = ""
        self.json_option = ""
        self.deselect_all = ""
        self.messages_checkbox = ""
        self.message_checkbox_class_name = ""
        self.top_text = ""
        self.date_block = ""
        self.year_dropdown = ""
        self.yesterday_year = ""
        self.month_dropdown = ""
        self.start_month = ""
        self.start_day = ""
        self.current_year = ""
        self.month_dropdown = ""
        self.current_month_dropdown = ""
        self.end_day = ""
        self.ok_button = ""
        self.create_file_button = ""
        self.available_copies_button = ""
        self.donwload_ready = ""
        self.download_button = ""

